@startnwdiag test_env
' Specify diagram name above, otherwise falls back on filename for output directory
' Note: this name must match with that of the deployment diagram

' Network definition
'
' Format: network <network_name> { ... }
network test.lan {
  ' Subnet definition
  '
  ' Format: address = <network-address>/<prefix-length>
  address = "172.26.0.0/24"

  ' Host definition
  '
  ' Notes:
  ' - By default the <description> attribute will be used as the resulting hostname;
  '   <host_identifier> is the fallback if <description> is unused.
  ' - Underscores in the hostname will be converted to hyphens, due to Unix conventions
  '
  ' Format: <host_identifier> [description = <description> address = <ipv4_address>, cpus = <amt_cores>, memory = <amt_gb_ram>, box="<base_box>", managed = <true|false>]
  dns [description = "dns", address = "172.26.0.20"]
  monitoring [description = "monitoring", address = "172.26.0.30", cpus = 2, memory = 2048]
  web [description = "web", address = "172.26.0.10"]
}

@endnwdiag