# One Vagrantfile to rule them all!
#
# This is a generic Vagrantfile that can be used without modification in
# a variety of situations. Hosts and their properties are specified in
# `vagrant-hosts.yml`. Provisioning is done by a shell script in the directory
# `provisioning/` with the same name as the host name.
#
# See https://github.com/bertvv/vagrant-shell-skeleton/ for details

require 'rbconfig'
require 'yaml'

# set default LC_ALL for all BOXES
ENV["LC_ALL"] = "en_US.UTF-8"

# Set your default base box here
DEFAULT_BASE_BOX = 'almalinux/9'

# Directory containing VM provisioning scripts
PROVISIONING_SCRIPT_DIR = 'scripts/'

# Maximum number of additional network interfaces VirtualBox supports
# (adapter 1 is always NAT, so 3 remain for other networks)
MAX_NETWORK_INTERFACES = 3

#
# No changes needed below this point
#

VAGRANTFILE_API_VERSION = '2'
PROJECT_NAME = '/' + File.basename(Dir.getwd)

# set custom vagrant-hosts file
vagrant_hosts = ENV['VAGRANT_HOSTS'] ? ENV['VAGRANT_HOSTS'] : 'vagrant-hosts.yml'
hosts = YAML.load_file(File.join(__dir__, vagrant_hosts))

# {{{ Helper functions

# Set options for the network interface configuration.
# Accepts either a host hash (single-IP format) or an interface hash
# from the 'networks' list (multi-interface format).
#
# All values are optional, and can include:
# - ip (default = DHCP)
# - netmask (default value = 255.255.255.0
# - mac
# - auto_config (if false, Vagrant will not configure this network interface
# - intnet (if true, an internal network adapter will be created instead of a
#   host-only adapter)
def network_options(iface)
  options = {}

  if iface.key?('ip')
    options[:ip] = iface['ip']
    options[:netmask] = iface['netmask'] ||= '255.255.255.0'
  else
    options[:type] = 'dhcp'
  end

  options[:mac] = iface['mac'].gsub(/[-:]/, '') if iface.key?('mac')
  options[:auto_config] = iface['auto_config'] if iface.key?('auto_config')
  options[:virtualbox__intnet] = true if iface.key?('intnet') && iface['intnet']
  options
end

def custom_synced_folders(vm, host)
  return unless host.key?('synced_folders')
  folders = host['synced_folders']

  folders.each do |folder|
    vm.synced_folder folder['src'], folder['dest'], folder['options']
  end
end

# Adds forwarded ports to your Vagrant machine
#
# example:
#  forwarded_ports:
#    - guest: 88
#      host: 8080
def forwarded_ports(vm, host)
  if host.has_key?('forwarded_ports')
    ports = host['forwarded_ports']

    ports.each do |port|
      vm.network "forwarded_port", guest: port['guest'], host: port['host']
    end
  end
end

# Configure network interfaces for a VM.
#
# Supports two formats in vagrant-hosts.yml:
#
# Single interface:
#   - name: myhost
#     ip: 192.168.0.10
#     netmask: 255.255.255.0
#
# Multi-interface:
#   - name: myrouter
#     networks:
#       - ip: 192.168.0.1
#         netmask: 255.255.255.0
#       - ip: 192.168.1.1
#         netmask: 255.255.255.0
def configure_networks(vm, host)
  if host.key?('networks')
    interfaces = host['networks']

    if interfaces.length > MAX_NETWORK_INTERFACES
      puts "WARNING: host '#{host['name']}' defines #{interfaces.length} interfaces, " \
           "but VirtualBox only supports #{MAX_NETWORK_INTERFACES}. " \
           "Only the first #{MAX_NETWORK_INTERFACES} will be configured."
      interfaces = interfaces.first(MAX_NETWORK_INTERFACES)
    end

    interfaces.each do |iface|
      vm.network :private_network, **network_options(iface)
    end
  elsif host.key?('ip')
    # Legacy single-interface format
    vm.network :private_network, **network_options(host)
  end
end

# }}}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  hosts.each do |host|
    config.vm.define host['name'] do |node|
      node.vm.box = host['box'] ||= DEFAULT_BASE_BOX
      node.vm.box_url = host['box_url'] if host.key? 'box_url'

      node.vm.hostname = host['name']
      configure_networks(node.vm, host)
      custom_synced_folders(node.vm, host)
      forwarded_ports(node.vm, host)
      # Allow setting a custom SSH username and password
      node.ssh.username = host['ssh_username'] if host.key? 'ssh_username'
      node.ssh.password = host['ssh_password'] if host.key? 'ssh_password'

      # VirtualBox-specific settings
      node.vm.provider :virtualbox do |vb|
        vb.memory = host['memory'] if host.key? 'memory'
        vb.cpus = host['cpus'] if host.key? 'cpus'

        # Add VM to a VirtualBox group
        # WARNING: if the name of the current directory is the same as the
        # host name, this will fail.
        vb.customize ['modifyvm', :id, '--groups', PROJECT_NAME]
      end

      # VMware Desktop-specific settings
      node.vm.provider :vmware_desktop do |vmw|
        # vmw.gui = true

        # Must be a multiple of 4MB
        vmw.vmx["memsize"] = host['memory'] if host.key? 'memory'
        vmw.vmx["numvcpus"] = host['cpus'] if host.key? 'cpus'
      end

      # Run provisioning script for the VM, if it exists.
      provisioning_script = PROVISIONING_SCRIPT_DIR + host['name'] + '.sh'
      if File.exist?(provisioning_script)
        node.vm.provision 'shell', path: provisioning_script
      end
    end
  end
end

# -*- mode: ruby -*-
# vi: ft=ruby :
