# role-config.yml
# Maps simplified role identifiers (as used in deployment diagrams) to their
# fully qualified Ansible role names and associated metadata.
#
# Notes:
#   - "fqcn" (the "Fully Qualified Collection Name") is the name that will be used
#     in the roles section of a host's play in the playbook. This is also the only
#     required key, all others are optional.
#   - "priority" directs the execution order of the role within a host's play.
#     Roles with lower priority values run first, and 100 is the default value.
#   - "depends_on" directs which roles must be applied on other hosts before this
#     role's host play runs. For example, hosts with the "dns_server_*" role must
#     complete their play before the hosts with "dns_client".
#   - "galaxy_roles" and "galaxy_collections" represent the Ansible Galaxy roles
#     and collections that must be installed on the Ansible control node prior
#     to running the playbook.
#   - "assets" represent the files under the "assets/" directory that are to be
#     copied to the Ansible control node prior to running the playbook.
#   - "host_vars" are the variables (in YAML format) written to the host's 
#     host_vars file. Sentinels prefixed with __DIAGRAM_ are placeholders which 
#     will be resolved by the converter at build time, derived from
#     diagram information.
#
# Format:
# roles:
#   <role_identifier>:
#     fqcn: <fqcn>
#     priority: <priority>
#     depends_on:
#       - <role_identifier>
#       ...
#     galaxy_roles:
#       - <ansible_galaxy_role_name>
#     galaxy_collections:
#       - <ansible_galaxy_collection_name>
#     host_vars:
#       <host_vars_in_yaml_format>
#   ...   
---
roles:
  # region dhcp_server
  dhcp_server:
    fqcn: bertvv.dhcp
    priority: 10
    depends_on:
      - dns_server_primary
      - dns_server_secondary
    galaxy_roles:
      - bertvv.dhcp
    host_vars:
      rhbase_firewall_allow_services:
        - dhcp
      dhcp_global_default_lease_time: 14400
      dhcp_global_max_lease_time: 14400
      dhcp_global_domain_name: __DIAGRAM_NETWORK_NAME__
      dhcp_global_broadcast_address: __DIAGRAM_BROADCAST__
      dhcp_global_subnet_mask: __DIAGRAM_NETMASK__
      dhcp_global_domain_name_servers: __DIAGRAM_DNS_SERVER_IPS__
      dhcp_subnets: __DIAGRAM_SUBNETS__
  # endregion

  # region dns_server_primary
  dns_server_primary:
    fqcn: dns_server
    priority: 10
    galaxy_roles:
      - bertvv.bind
    host_vars:
      rhbase_firewall_allow_services:
        - dns
        - prometheus-node-exporter
      rhbase_firewall_allow_ports:
        - 9119/tcp
      bind_acls:
        - name: acl1
          match_list: __DIAGRAM_BIND_ACL_SUBNETS__
      bind_allow_query:
        - any
      bind_listen_ipv4:
        - any
      bind_dnssec_enable: false
      bind_dnssec_validation: false
      bind_forward_only: true
      bind_forwarders:
        - 10.0.2.3
        - 1.1.1.1
      bind_recursion: true
      bind_allow_transfer: __DIAGRAM_DNS_SECONDARY_IPS__
      bind_zones: __DIAGRAM_BIND_ZONES_PRIMARY__
  # endregion

  # region dns_server_secondary
  dns_server_secondary:
    fqcn: dns_server # Same as dns_server_primary, as it's virtually the same role with just different host_vars
    priority: 10
    galaxy_roles:
      - bertvv.bind
    host_vars:
      rhbase_firewall_allow_ports:
        - 53/tcp
        - 53/udp
        - 9100/tcp
        - 9119/tcp
      bind_acls:
        - name: acl1
          match_list: __DIAGRAM_BIND_ACL_SUBNETS__
      bind_allow_query:
        - any
      bind_listen_ipv4:
        - any
      bind_dnssec_enable: false
      bind_dnssec_validation: false
      bind_forward_only: true
      bind_forwarders:
        - 10.0.2.3
        - 1.1.1.1
      bind_recursion: true
      bind_zones: __DIAGRAM_BIND_ZONES_SECONDARY__
  # endregion

  # region dns_client
  dns_client:
    fqcn: dns_client
    priority: 20
    depends_on:
      - dns_server_primary
      - dns_server_secondary
    host_vars:
      dns_servers: __DIAGRAM_DNS_SERVER_IPS__
  # endregion

  # region monitoring_server
  monitoring_server:
    fqcn: monitoring_server
    priority: 20
    depends_on:
      - dns_server_primary
      - dns_server_secondary
    galaxy_collections:
      - prometheus.prometheus
      - grafana.grafana
    assets:
      - ansible/files/grafana/default.yml
    host_vars:
      grafana_alerting: {}
      grafana_dashboards_dir: /var/lib/grafana/dashboards
      grafana_datasources:
        - name: prometheus
          type: prometheus
          access: proxy
          url: "http://localhost:9090"
          basicAuth: false
      grafana_provisioning_synced: true
      grafana_security:
        admin_user: admin
        admin_password: root
      prometheus_scrape_configs: __DIAGRAM_SCRAPE_CONFIGS__
      rhbase_firewall_allow_ports:
        - 53/tcp
        - 53/udp
        - 3000/tcp
  # endregion

  # region apache_exporter
  apache_exporter:
    fqcn: prometheus.prometheus.apache_exporter
    priority: 50
    galaxy_collections:
      - prometheus.prometheus
    assets:
      - ansible/files/grafana/dashboards/apache_exporter.json
    host_vars:
      rhbase_firewall_allow_ports:
        - 9117/tcp
      apache_exporter_port: 9117
      apache_exporter_uri: "http://localhost/server-status/?auto"
      apache_exporter_web_listen_address: "0.0.0.0:9117"
      httpd_status_enable: true

  # endregion

  # region bind_exporter
  bind_exporter:
    fqcn: prometheus.prometheus.bind_exporter
    priority: 50
    galaxy_collections:
      - prometheus.prometheus
    assets:
      - ansible/files/grafana/dashboards/bind_exporter.json
    host_vars:
      rhbase_firewall_allow_ports:
        - 9119/tcp
      bind_exporter_port: 9119
      bind_statistics_channels: true
  # endregion

  # region mysqld_exporter
  mysqld_exporter:
    fqcn: prometheus.prometheus.mysqld_exporter
    priority: 50
    galaxy_collections:
      - prometheus.prometheus
    assets:
      - ansible/files/grafana/dashboards/mysqld_exporter.json
    host_vars:
      rhbase_firewall_allow_ports:
        - 9104/tcp
      rhbase_install_packages:
        - python3-PyMySQL
      mysqld_exporter_enabled_collectors:
        - info_schema.processlist
        - info_schema.innodb_metrics
        - info_schema.tablestats
        - info_schema.tables
        - info_schema.userstats
        - engine_innodb_status
        - slave_status
      mysqld_exporter_port: 9104
      mysqld_exporter_socket: "/var/lib/mysql/mysql.sock"
      mysqld_exporter_web_listen_address: "0.0.0.0:9104"
  # endregion

  # region node_exporter
  node_exporter:
    fqcn: prometheus.prometheus.node_exporter
    priority: 50
    galaxy_collections:
      - prometheus.prometheus
    assets:
      - ansible/files/grafana/dashboards/node_exporter.json
    host_vars:
      rhbase_firewall_allow_ports:
        - 9100/tcp
      node_exporter_port: 9100
  # endregion

  # region web_server
  web_server:
    fqcn: web_server
    priority: 10
    galaxy_roles:
      - bertvv.httpd
    assets:
      - ansible/files/ca.crt
      - ansible/files/ca.key
      - ansible/files/db.sql
      - ansible/files/test.php
    host_vars:
      rhbase_firewall_allow_ports:
        - 80/tcp
        - 443/tcp
      rhbase_install_packages:
        - httpd
        - mariadb-server
        - php-fpm
        - php-mysqlnd
        - python3-PyMySQL
      rhbase_repositories:
        - epel-release
      rhbase_start_services:
        - httpd
        - mariadb
      rhbase_selinux_booleans:
        - httpd_can_network_connect
      httpd_ssl_certificate_key_file: "ca.key"
      httpd_ssl_certificate_file: "ca.crt"
      db_user: "appuser"
      db_name: "appdb"
      db_password: "let me in"
  # endregion
