@startuml test_env
/'
Diagram name definition

Format: @startuml <diagram_name>

Note: if no diagram name is specified, the filename is used as a fallback for
naming the output directory. This name should match the network diagram's.
'/

/'
Required line; qualifies component names with their parent host identifier,
preventing name collisions for roles that appear on multiple hosts (e.g.
dns.node_exporter vs web.node_exporter).
'/
set separator .

' Purely visual, won't have any effect on the parser
left to right direction

/'
Host definition

Notes:
- By default <description> will be used as the resulting hostname;
<host_identifier> is the fallback if <description> is unused.
- Underscores in the hostname will be converted to hyphens, due to Unix conventions.

Format:
node <host_identifier> as <description>
'/
node web as "web" {
    /'
    Role definition

    Format:
    component <role_identifier>
    '/
    component apache_exporter
    component dns_client
    component mysqld_exporter
    component node_exporter
    component web_server
}

node dns as "dns" {
    component bind_exporter
    component dns_client
    component dns_server_primary
    component node_exporter
}

node mon as "monitoring" {
    component dns_client
    component monitoring_server
    component node_exporter
}

/'
Role-to-role connections

Note: Arrows must always point from left to right, but can be styled according to
      https://crashedmind.github.io/PlantUMLHitchhikersGuide/layout/layout.html

Format:
<host_identifier>.<role_identifier> --> <host_identifier>.<role_identifier>
'/
dns.dns_client -[#teal]-> dns.dns_server_primary

mon.dns_client -[#teal]-> dns.dns_server_primary
mon.monitoring_server -[#coral]-> dns.bind_exporter
mon.monitoring_server -[#coral]-> dns.node_exporter
mon.monitoring_server -[#coral]-> mon.node_exporter
mon.monitoring_server -[#coral]-> web.apache_exporter
mon.monitoring_server -[#coral]-> web.mysqld_exporter
mon.monitoring_server -[#coral]-> web.node_exporter

web.dns_client -[#teal]-> dns.dns_server_primary

@enduml