@startuml test_env
' Fix roles being reused over different nodes
' This line makes sure that objects with the same name (nota)
set separator /


' Format: node <identifier> <<<type>>> as <description>
node central_router <<router>> as "central_router" {
    component "router"
}

node alpha_dns as "alpha-dns" {
    component "dns_server"
    component "dns_client"
    component "bind_exporter"
}

node alpha_monitoring as "alpha-monitoring" {
    component "dns_client"
    component "prometheus"
    component "grafana"
}

node alpha_web as "alpha-web" {
    ' artifact "ca.cert"
    ' artifact "ca.key"
    ' artifact "db.sql"
    ' artifact "test.php"
    component "dns_client"
    component "web_server"
    component "mysqld_exporter"
}

dns_server -- alpha_monitoring
dns_server -- alpha_web
dns_server -- alpha_web

@enduml