@startnwdiag test_env
// @startnwdiag <optional_diagram_name> --> Start of network diagram
  // (Local) network specification
  //
  // Format: network <network_name> { ... }
  network network-alpha {
    // Optional subnet specification
    address = 172.26.0.0/24

    // Host(s) specification
    //
    // Format: <hostname> [address = <ipv4_address>]
    //
    //
    alpha-web [address = 172.26.0.10];
    alpha-dns [address = 172.26.0.20];
    alpha-monitoring [address = 172.26.0.30];
  }

  network network-beta {
    address = 172.26.10.0/24

    beta-workstation-1 [address = 172.26.10.10];
    beta-workstation-2 [address = 172.26.10.20];
  }
// @endnwdiag --> End of network diagram
@endnwdiag