@startuml infra_auto_env
set separator .
left to right direction

node srv001 {
    component bind_exporter
    component dns_client
    component dns_server_primary
    component node_exporter
}

node srv002 {
    component bind_exporter
    component dns_client
    component dns_server_secondary
    component node_exporter
}

node srv003 {
    component dhcp_server
    component dns_client
    component node_exporter
}

node srv004 {
    component dns_client
    component monitoring_server
    component node_exporter
}

node srv100 {
    component apache_exporter
    component dns_client
    component mysqld_exporter
    component node_exporter
    component web_server
}

srv001.dns_client -[#teal]-> srv001.dns_server_primary
srv001.dns_client -[#teal]-> srv002.dns_server_secondary

srv002.dns_client -[#teal]-> srv001.dns_server_primary
srv002.dns_client -[#teal]-> srv002.dns_server_secondary

srv003.dns_client -[#teal]-> srv001.dns_server_primary
srv003.dns_client -[#teal]-> srv002.dns_server_secondary

srv004.dns_client -[#teal]-> srv001.dns_server_primary
srv004.dns_client -[#teal]-> srv002.dns_server_secondary
srv004.monitoring_server -[#coral]-> srv001.bind_exporter
srv004.monitoring_server -[#coral]-> srv001.node_exporter
srv004.monitoring_server -[#coral]-> srv002.bind_exporter
srv004.monitoring_server -[#coral]-> srv002.node_exporter
srv004.monitoring_server -[#coral]-> srv003.node_exporter
srv004.monitoring_server -[#coral]-> srv004.node_exporter
srv004.monitoring_server -[#coral]-> srv100.apache_exporter
srv004.monitoring_server -[#coral]-> srv100.mysqld_exporter
srv004.monitoring_server -[#coral]-> srv100.node_exporter

srv100.dns_client -[#teal]-> srv001.dns_server_primary
srv100.dns_client -[#teal]-> srv002.dns_server_secondary

@enduml