# ansible/host_vars/alpha-monitoring.yml
---
# region bertvv.rhbase
rhbase_firewall_allow_services:
  - dns
  - grafana
  # - prometheus-node-exporter
# endregion

# region prometheus.prometheus.prometheus
prometheus_scrape_configs:
  - job_name: "node_exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "localhost:9100"
          - "ns1.alpha.lan:9100"
          # - "172.16.128.1:9100"
          # - "ns2.alpha.lan:9100"
          # - "172.16.128.2:9100"
          # - "dhcp.alpha.lan:9100"
          # - "172.16.128.3:9100"
          - "www.alpha.lan:9100"
        # - "172.16.128.100:9100"
  - job_name: "bind_exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "ns1.alpha.lan:9119"
        # - "ns2.alpha.lan:9119"
  - job_name: "mysqld_exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "www.alpha.lan:9104"
# endregion

# region grafana.grafana.grafana
grafana_security:
  admin_user: admin
  admin_password: root

grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: "http://localhost:9090"
    basicAuth: false

grafana_dashboards:
  - dashboard_id: 1860 # Node Exporter Full
    revision_id: 42
    datasource: prometheus
  - dashboard_id: 12172 # Bind9 Full
    revision_id: 6
    datasource: prometheus
  - dashboard_id: 14057 # MySQL Exporter Quickstart and Dashboard
    revision_id: 1
    datasource: prometheus

grafana_alerting: {}
# endregion