# ansible/host_vars/dns.yml
---
# region bertvv.rhbase
rhbase_firewall_allow_ports:
  - 53/tcp # DNS
  - 53/udp # DNS
  - 9100/tcp # Node Exporter
  - 9119/tcp # BIND exporter
# endregion

# region bertvv.bind
bind_acls:
  - name: acl1
    match_list:
      - 172.26.0.0/24

bind_allow_query: ["any"]

bind_listen_ipv4: ["any"]

bind_dnssec_enable: false

bind_dnssec_validation: false

bind_forward_only: true

bind_forwarders:
  - 10.0.2.3
  - 1.1.1.1

bind_recursion: true

# bind_allow_transfer: # For secondary DNS

bind_statistics_channels: true

# bind_statistics_allow:
#   - '127.0.0.1'

# bind_statistics_host: 127.0.0.1

# bind_statistics_port: 8053

bind_zones:
  - name: alpha.lan
    type: primary
    primaries:
      - "{{ hostvars['dns']['ansible_host'] }}"
    name_servers:
      - dns.alpha.lan.
    allow_update:
      - "{{ hostvars['dns']['ansible_host'] }}"
    # also_notify: # For secondary DNS
    hosts:
      - name: dns
        ip: "{{ hostvars['dns']['ansible_host'] }}"
        aliases:
          - ns
          - ns1
      - name: monitoring
        ip: "{{ hostvars['monitoring']['ansible_host'] }}"
        aliases:
          - mon
      - name: web
        ip: "{{ hostvars['web']['ansible_host'] }}"
        aliases:
          - web
      - name: control
        ip: "{{ control_node_ip }}"
      - name: "@" # Enables "http://mydomain.com/"
        ip: "{{ hostvars['web']['ansible_host'] }}"
        aliases:
          - www
    networks:
      - "172.26"
# endregion