# ansible/host_vars/web.yml
---
# region bertvv.rh-base
rhbase_firewall_allow_ports:
  - 80/tcp
  - 443/tcp
  - 9100/tcp # Node Exporter
  - 9104/tcp # MySQL Server Exporter

rhbase_install_packages:
  - bash-completion
  - bind-utils
  - git
  - httpd
  - mariadb-server
  - nano
  - php-fpm
  - php-mysqlnd
  - python3-PyMySQL
  - setroubleshoot-server
  - tree
  - vim-enhanced
  - wget

rhbase_start_services:
  - httpd
  - mariadb

rhbase_selinux_booleans:
  - httpd_can_network_connect
# endregion

# region bertvv.httpd
httpd_ssl_certificate_key_file: "ca.key"
httpd_ssl_certificate_file: "ca.crt"
httpd_status_enable: true
# endregion

# region role_web_server
db_user: "appuser"
db_name: "appdb"
db_password: "let me in"

# endregion

# region prometheus.prometheus.mysql_exporter
# mysqld_exporter_enabled_collectors:
#   - info_schema.processlist
#   - info_schema.innodb_metrics
#   - info_schema.tablestats
#   - info_schema.tables
#   - info_schema.userstats
#   - engine_innodb_status
#   - slave_status

# mysqld_exporter_port: "9104"
# mysqld_exporter_socket: "/var/lib/mysql/mysql.sock"
# mysqld_exporter_web_listen_address: "0.0.0.0:9104"
# endregion
