# ansible/inventory_test_env.yml
---
all:
  children:
    # <network_name>
    network-alpha:
      # Required vars for local testing with Vagrant
      vars:
        ansible_user: vagrant
        ansible_ssh_password: vagrant
        ansible_become: true
      hosts:
        # <hostname>
        alpha-web:
          # <ipv4_address>
          ansible_host: 172.26.0.10
        alpha-dns:
          ansible_host: 172.26.0.20
        alpha-monitoring:
          ansible_host: 172.26.0.30
    # network-beta:
    #   vars:
    #     ansible_user: vagrant
    #     ansible_ssh_password: vagrant
    #     ansible_become: true
    #   hosts:
    #     beta_workstation_1:
    #       ansible_host: 172.26.10.10
    #     beta_workstation_2:
    #       ansible_host: 172.26.10.20
    # routers:
    #   hosts:
    #     test-env-router:
    #       ansible_host: 172.26.0.1
    #       ansible_user: vyos
    #       ansible_ssh_pass: vyos
    #       ansible_network_os: vyos
    #       ansible_connection: network_cli