# ansible/requirements.yml
---
roles:
  - name: bertvv.rh-base
  - name: bertvv.httpd
  - name: bertvv.bind
  # - name: bertvv.dhcp
collections:
  - name: prometheus.prometheus
  - name: grafana.grafana