# ansible/router-config.yml
---
- name: Configure test-env-router
  hosts: test-env-router
  tasks:
    - name: Set the IP address of the internal interface
      vyos.vyos.vyos_l3_interfaces:
        config:
          - name: eth1
            ipv4:
              - address: "{{ hostvars['test-env-router']['ansible_host'] }}"/16
    - name: Add a description to both interfaces
      vyos.vyos.vyos_interfaces:
        config:
          - name: eth0
            description: WAN
          - name: eth1
            description: LAN
    - name: Set the host name of the router
      vyos.vyos.vyos_hostname:
        config:
          hostname: test-env-router
    - name: Enable NAT on the router
      vyos_config:
        lines:
        - set nat source rule 10 outbound-interface name eth0
        - set nat source rule 10 source address '172.26.0.0/16'
        - set nat source rule 10 translation address 'masquerade'
    # - name: Set a port forwarding rule that forwards HTTP/HTTPS traffic on the appropriate ports to the web server
    # - name: Enable and configure the firewall on the router
    - name: Save the (committed) config
      vyos_config:
        save: true